[project]
name = "leaf_image_database"
version = "1.0.0"
description = "Hệ thống cơ sở dữ liệu lưu trữ và tìm kiếm ảnh lá cây"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
dependencies = []